version: '3'
services:
  ### PHP-FPM Container
  php-fpm:
    build: ./build/php-fpm
    volumes:
      - ${SRC_PATH}:${DEST_PATH}
    expose:
      - "9000"
    links:
      - mysql
      - redis

  ### NGINX Container
  nginx:
    build: ./build/nginx
    volumes:
      - ${LOGS_PATH}/nginx/:/var/log/nginx
      - ${SRC_PATH}:${DEST_PATH}
      - ./data/nginx/sites-available:/etc/nginx/sites-available
    ports:
      - "4380:80"
      - "4443:443"
    links:
      - php-fpm

  redis:
    image: redis
    expose:
      - "6379"
      
  ### MySQL Container
  mysql:
    build: ./build/mysql
    volumes:
      - ${VOLUME_PATH}:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}

  ### Application Code Container
  application:
    build: ./build/application
  workspace:
    build: ./build/workspace
    volumes:
      - ${SRC_PATH}:${DEST_PATH}
    links:
      - mysql
      - redis

  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - mysql
    volumes:
      - ${VOLUME_PATH}/backup:/backup
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASS=${DB_ROOT_PASS}
      - MAX_BACKUPS=15
      - INIT_BACKUP=0
      # Every day at 03:00
      - CRON_TIME=0 3 * * *
    restart: unless-stopped 

volumes:
  src:
